# Global settings applied to the whole site.
#
# “base” is the directory to change to before starting build. If you set base:
#        that is where we will look for package.json/.nvmrc/etc, not repo root!
# “command” is your build command.
# “publish” is the directory to publish (relative to the root of your repo).

[build]
  publish = "public"



  [[redirects]]
from = "/messages"
to = "/message.html"
status = 200

 [[redirects]]
from = "/registration"
to = "/registrationPage.html"
status = 200

 [[redirects]]
from = "/500"
to = "/500ServerError.html"
status = 200

 [[redirects]]
from = "/404"
to = "/404notFound.html"
status = 200

 [[redirects]]
from = "/users"
to = "/listOfChats.html"
status = 200

 [[redirects]]
from = "/profile"
to = "/profilePage.html"
status = 200


  [[redirects]]
from = "/*"
to = "/404notFound.html"
status = 200

